// CurrentAddress
export const UPDATE_CURRENT_ADDRESS = 'UPDATE_CURRENT_ADDRESS'
export const UPDATE_CURRENT_LAT = 'UPDATE_CURRENT_LAT'
export const UPDATE_CURRENT_LNG = 'UPDATE_CURRENT_LNG'
export const CURRENT_TAG = 'CURRENT_TAG'
export const UPDATE_PROFILE_PICTURE = 'UPDATE_PROFILE_PICTURE'
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS'


//AppointementActions
export const UPDATE_PAYMENT_MODE = 'UPDATE_PAYMENT_MODE'

//Order
export const ADD_TO_CART = 'ADD_TO_CART'
export const UPDATE_PHARM_ID = 'UPDATE_PHARM_ID'
export const RESET = 'RESET'
export const UPDATE_SUBTOTAL = 'UPDATE_SUBTOTAL' 
export const UPDATE_PROMO = 'UPDATE_PROMO' 
export const CALCULATE_TOTAL = 'CALCULATE_TOTAL'
export const TAX_LIST = 'TAX_LIST'
export const UPDATE_DELIVERY_CHARGE = 'UPDATE_DELIVERY_CHARGE' 
{/*
export const UPDATE_PROMO = 'UPDATE_PROMO' 
export const UPDATE_DISCOUNT = 'UPDATE_DISCOUNT' 
export const UPDATE_TOTAL = 'UPDATE_TOTAL'


export const UPDATE_TAX = 'UPDATE_TAX'
export const CALCULATE_TOTAL = 'CALCULATE_TOTAL'
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS'
export const UPDATE_PHARMACIES = 'UPDATE_PHARMACIES'
export const UPDATE_PAYMENT_MODE = 'UPDATE_PAYMENT_MODE'
*/}

//Lab Order
export const UPDATE_LAB_ID = 'UPDATE_LAB_ID'
export const UPDATE_CURRENT_LAB_ID = 'UPDATE_CURRENT_LAB_ID'
export const UPDATE_LAB_ADD_TO_CART = 'UPDATE_LAB_ADD_TO_CART'
export const UPDATE_LAB_SUBTOTAL = 'UPDATE_LAB_SUBTOTAL' 
export const UPDATE_LAB_PROMO = 'UPDATE_LAB_PROMO' 
export const UPDATE_LAB_CALCULATE_TOTAL = 'UPDATE_LAB_CALCULATE_TOTAL'
export const UPDATE_LAB_DISCOUNT = 'UPDATE_LAB_DISCOUNT' 
export const UPDATE_LAB_TOTAL = 'UPDATE_LAB_TOTAL'
export const UPDATE_LAB_TAX_LIST = 'UPDATE_LAB_TAX_LIST'
export const UPDATE_LAB_TAX = 'UPDATE_LAB_TAX'
export const LAB_RESET = 'LAB_RESET'
export const UPDATE_LAB_PATIENT_NAME = 'UPDATE_LAB_PATIENT_NAME'
export const UPDATE_LAB_PATIENT_DOB = 'UPDATE_LAB_PATIENT_DOB'
export const UPDATE_LAB_PATIENT_GENDER_ID = 'UPDATE_LAB_PATIENT_GENDER_ID'
export const UPDATE_LAB_PATIENT_GENDER_NAME = 'UPDATE_LAB_PATIENT_GENDER_NAME'
export const UPDATE_LAB_PATIENt_PAYMENT_MODE = 'UPDATE_LAB_PATIENt_PAYMENT_MODE'
export const UPDATE_LABS = 'UPDATE_LABS'

//Prescription Order
export const UPDATE_PRESCRIPTION_ID = 'UPDATE_PRESCRIPTION_ID'
export const UPDATE_PRESCRIPTION_DETAILS = 'UPDATE_PRESCRIPTION_DETAILS'
